export default {
  REQUEST_MOVIES: 'REQUEST_MOVIES',
  UPDATE_MOVIES_LIST:'UPDATE_MOVIES_LIST',
  MOVIES_ARE_LOADING:'MOVIES_ARE_LOADING',

  UPDATE_INPUT: 'UPDATE_INPUT',
  TOGGLE_INPUT: 'TOGGLE_INPUT', 
  FOCUS_INPUT: 'FOCUS_INPUT',

  UPDATE_MOVIES_ERROR: 'UPDATE_MOVIES_ERROR'
}